map:
  resolution: 0.2
  free_threshold: 0.13
  occupancy_threshold: 0.7
  clamping_min: 0.001
  clamping_max: 0.9999999
  probability_hit: 0.99
  probability_miss: 0.33
  initial_count: 10
  block_size: 30
  lock_at_max_clamp: false
  width: 5
  height: 5
  depth: 5
  origin_x: -0.5
  origin_y: -0.5
  origin_z: -0.5
  track_changes: false
